reviews:
  request_changes_workflow: true
  auto_review:
    enabled: true
  sequence_diagrams: true
  high_level_summary: true
  finishing_touches: 
    docstrings: 
      enabled: true
    unit_tests: 
      enabled: true